# 用于数据加载的工作线程数量。在训练过程中，数据加载是一个并行操作，可以加快数据预处理和加载的速度。线程数量通常设置为CPU核心数的倍数，以充分利用硬件资源。
WORKERS: 8
#  打印训练信息的频率，通常是指每个打印周期内打印一次训练损失、准确率等信息的步数。这个参数可以帮助开发者监控训练进度和性能。
PRINT_FREQ: 10

DATASET:
  DATASET: 'custom_coco'
  TRAIN_FILE:
    - 'images/dutaer/train/1/train_anno.json'
    - 'images/dutaer/train/2/train_anno.json'
    - 'images/dutaer/train/3/train_anno.json'
#    - '/root/autodl-tmp/shuju/HandPose-v2/HandPose-v2/train/train_anno.json'
#    - '/root/autodl-tmp/shuju/HandPose-v3/HandPose-v3/train/train_anno.json'
  TEST_FILE: 'images/dutar/test/test_anno.json'
#     - 'images/dutaer/test/1_2_3/test_anno.json'
#    - 'images/dutaer/test/2/test_anno.json'
#    - 'images/dutaer/test/2_3/test_anno.json'
#    - 'images/dutaer/test/3/test_anno.json'
#    - 'E:/BaiduNetdiskDownload/shuju/HandPose-v1/HandPose-v1/train/train_anno.json'
#    - 'E:/BaiduNetdiskDownload/shuju/HandPose-v2/HandPose-v2/train/train_anno.json'
#    #    - '/root/autodl-tmp/shuju/HandPose-v3/HandPose-v3/train/train_anno.json'
#  TEST_FILE: 'E:/BaiduNetdiskDownload/shuju/HandPose-v1/HandPose-v1/test/test_anno.json'
  FLIP: true # 这可能表示在处理图像或者动画时，是否应用了翻转操作。true 表示翻转将被应用。
  ROT_FACTOR: 45 # 这可能指定了旋转的角度，这里是45度。
  SCALE_FACTOR: 0.3 # 这个数值可能指定了缩放的比例，这里是0.3，意味着原始尺寸的30%。
  SCALE_RATE: 1.25 # 这个数值可能指定了缩放的速率或者增长的比例，这里是1.25，意味着最终尺寸为原始尺寸的125%。
  JOINT_IDS: [ ] # 这个列表可能被用来指定骨骼或者关节的ID，当前为空。
  FLIP_PAIRS: [ ] # 这个列表可能被用来指定需要进行翻转的关节对，当前为空。
#  SKELETON: [ ]
#  SKELETON: [ [ 0, 1 ], [ 1, 2 ], [ 2, 3 ], [ 3, 4 ], [ 0, 5 ], [ 5, 6 ], [ 6, 7 ], [ 7, 8 ],  [ 5, 9 ], [ 9, 10 ], [ 10, 11 ], [ 11, 12 ], [ 9, 13 ], [ 13, 14 ], [ 14, 15 ], [ 15, 16 ], [ 13, 17 ], [ 17, 18 ], [ 18, 19 ], [ 19, 20 ], [ 0, 17 ] ]
  SKELETON: [ [
                0,
                2
              ],
              [
                2,
                4
              ],
              [
                4,
                6
              ],
              [
                6,
                8
              ],
              [
                8,
                10
              ],
              [
                10,
                12
              ],
              [
                12,
                14
              ],
              [
                14,
                16
              ],
              [
                16,
                18
              ],
              [
                18,
                20
              ],
              [
                20,
                22
              ],
              [
                22,
                24
              ],
              [
                24,
                26
              ],
              [
                26,
                28
              ],
              [
                28,
                30
              ],
              [
                30,
                32
              ],
              [
                1,
                3
              ],
              [
                3,
                5
              ],
              [
                5,
                7
              ],
              [
                7,
                9
              ],
              [
                9,
                11
              ],
              [
                11,
                13
              ],
              [
                13,
                15
              ],
              [
                15,
                17
              ],
              [
                17,
                19
              ],
              [
                19,
                21
              ],
              [
                21,
                23
              ],
              [
                23,
                25
              ],
              [
                25,
                27
              ],
              [
                27,
                29
              ],
              [
                29,
                31
              ],
              [
                31,
                33
              ]
  ]

MODEL:
  NAME: 'hrnet_w32'
  OUT_TYPE: 'gaussian' # gaussian,offset
  PRETRAINED: 'data/pretrained/imagenet/hrnet_w32-36af842e.pth'
  INIT_WEIGHTS: true
  IMAGE_SIZE: [ 192,192 ] #图像的尺寸被设定为192像素乘以192像素
  HEATMAP_SIZE: [ 48,48 ] #热力图的尺寸被设定为48像素乘以48像素
  #  模型或算法预期要检测或估计的人体关键点（joints）总数为21个
  NUM_JOINTS: 34
  # 用于设置一个多阶段（multi-stage）的神经网络架构，可能是用于人体姿态估计或类似任务的模型。这些参数配置了网络的不同方面，
  # 包括每个阶段的模块数量、分支数量、块类型、块的数量、通道数量以及融合方法。下面是对这些参数的解释：
  EXTRA:
    # SIGMA: 高斯核的标准差，用于生成热力图。在人体姿态估计中，热力图通常用于表示关键点在图像中的位置，
    # 高斯核用于平滑这个位置，SIGMA值决定了平滑的程度。
    SIGMA: 2
    FINAL_CONV_KERNEL: 1 # 最终卷积层的核大小。在生成热力图时，这个参数决定了最终特征图的分辨率。
    NUM_LAYERS: 32 #网络中层的总数。这可能指的是整个网络中层的堆叠数量。
    PRETRAINED_LAYERS: #这些是在训练过程中可以加载预训练权重的层的列表。这意味着这些层可能之前在另
    # 一个任务或数据集上训练过，可以用来初始化当前模型的一部分。
      - 'conv1'
      - 'bn1'
      - 'conv2'
      - 'bn2'
      - 'layer1'
      - 'transition1'
      - 'stage2'
      - 'transition2'
      - 'stage3'
      - 'transition3'
      - 'stage4'
    STAGE2:
      NUM_MODULES: 1 # 每个阶段的模块数量
      NUM_BRANCHES: 2 #每个阶段的分支数量。每个分支可能处理不同尺度的特征图。
      BLOCK: BASIC # 每个阶段的分支数量。每个分支可能处理不同尺度的特征图。
      NUM_BLOCKS: # 每个分支中的块数量
        - 4
        - 4
      NUM_CHANNELS: # 每个分支的通道数量。
        - 32
        - 64
      FUSE_METHOD: SUM # 分支融合的方法，这里都是SUM，意味着不同分支的特征图通过相加的方式融合。
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 32
        - 64
        - 128
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
      NUM_CHANNELS:
        - 32
        - 64
        - 128
        - 256
      FUSE_METHOD: SUM
LOSS:
  USE_TARGET_WEIGHT: true #意味着在计算损失时，将使用目标权重（target weight）
TRAIN:
  BATCH_SIZE: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME: false # 是否从之前保存的检查点（checkpoint）恢复训练。如果设置为true，则训练将从检查点中记录的周期继续。
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP: #学习率衰减的步长。在这个例子中，学习率将在第120和第170个周期时减少LR_FACTOR倍。
    - 60
    - 90
  WD: 0.001 # 权重衰减（weight decay）系数，用于惩罚大权重，防止过拟合。
  GAMMA1: 0.99 # 这些参数可能与某些特定的学习率调整策略有关，例如AdamW优化器中的参数。在普通的Adam优化器中，这些参数可能不是标准配置。
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false # 是否使用Nesterov动量。这是一种动量优化的变种，可以进一步提高优化速度。
TEST:
  BATCH_SIZE: 64
  # COCO数据集中用于测试的人体检测结果的文件路径。这个文件通常包含了人体边界框的信息，这些信息可以用于人体姿态估计。
  COCO_BBOX_FILE: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'
  BBOX_THRE: 1.0 #  边界框阈值，用于过滤掉置信度较低的边界框。只有置信度高于这个阈值的边界框才会用于后续的姿态估计。
  FLIP_TEST: true # 是否在测试时对图像进行水平翻转。翻转后的图像会被送入网络进行预测，然后将预测结果与原始图像的预测结果进行合并，以提高关键点的定位精度。
  IMAGE_THRE: 0.0 # 图像阈值，用于过滤掉某些图像。这个参数的具体用途取决于实现细节，可能用于排除质量较差或不符合特定条件的图像。
  IN_VIS_THRE: 0.2 # 可见性阈值，用于过滤掉部分遮挡或不可见的关键点。只有可见性高于这个阈值的关键点才会被考虑。
  MODEL_FILE: '' # 可见性阈值，用于过滤掉部分遮挡或不可见的关键点。只有可见性高于这个阈值的关键点才会被考虑。
  NMS_THRE: 1.0 # 非极大值抑制（Non-maximum suppression）的阈值，用于在姿态估计过程中去除冗余的关键点。NMS用于确保每个关键点只被检测一次。
  OKS_THRE: 0.9 # OKS（Object Keypoint Similarity）阈值，用于评估预测的关键点与真实关键点之间的相似度。在COCO数据集的人体姿态估计任务中，OKS是常用的评估指标。
  USE_GT_BBOX: true # 是否使用真实的边界框（Ground Truth Bounding Boxes）。如果设置为true，则使用数据集中的真实边界框进行姿态估计；如果设置为false，则可能使用模型预测的边界框或其他来源的边界框。
DEBUG:
  DEBUG: true # 是否开启调试模式。
  SAVE_BATCH_IMAGES_GT: true # 是否保存批处理中的图像和它们的真实标注。这可以帮助开发者可视化模型输入的数据，以及与之对应的真实关键点位置。
  SAVE_BATCH_IMAGES_PRED: true # 是否保存批处理中的图像和模型的预测结果。这可以帮助开发者比较模型的预测关键点与真实关键点的差异。
  SAVE_HEATMAPS_GT: true # 是否保存批处理中的真实热力图。在人体姿态估计中，热力图表示了每个关键点在图像中的概率分布。保存真实热力图可以帮助开发者评估模型是否能够准确地学习关键点的分布。
  SAVE_HEATMAPS_PRED: true # 是否保存批处理中的预测热力图。通过比较预测热力图和真实热力图，开发者可以直观地看到模型在关键点定位方面的性能。
